//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="RealSenseServer")]
public interface RealSenseServer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestDepthImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestDepthImageResponse")]
    byte[] LatestDepthImage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestDepthImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestDepthImageResponse")]
    System.Threading.Tasks.Task<byte[]> LatestDepthImageAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestYUVImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestYUVImageResponse")]
    byte[] LatestYUVImage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestYUVImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestYUVImageResponse")]
    System.Threading.Tasks.Task<byte[]> LatestYUVImageAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestRGBImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestRGBImageResponse")]
    byte[] LatestRGBImage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestRGBImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestRGBImageResponse")]
    System.Threading.Tasks.Task<byte[]> LatestRGBImageAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestJPEGImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestJPEGImageResponse")]
    byte[] LatestJPEGImage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealSenseServer/LatestJPEGImage", ReplyAction="http://tempuri.org/RealSenseServer/LatestJPEGImageResponse")]
    System.Threading.Tasks.Task<byte[]> LatestJPEGImageAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RealSenseServerChannel : RealSenseServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RealSenseServerClient : System.ServiceModel.ClientBase<RealSenseServer>, RealSenseServer
{
    
    public RealSenseServerClient()
    {
    }
    
    public RealSenseServerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RealSenseServerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RealSenseServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RealSenseServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public byte[] LatestDepthImage()
    {
        return base.Channel.LatestDepthImage();
    }
    
    public System.Threading.Tasks.Task<byte[]> LatestDepthImageAsync()
    {
        return base.Channel.LatestDepthImageAsync();
    }
    
    public byte[] LatestYUVImage()
    {
        return base.Channel.LatestYUVImage();
    }
    
    public System.Threading.Tasks.Task<byte[]> LatestYUVImageAsync()
    {
        return base.Channel.LatestYUVImageAsync();
    }
    
    public byte[] LatestRGBImage()
    {
        return base.Channel.LatestRGBImage();
    }
    
    public System.Threading.Tasks.Task<byte[]> LatestRGBImageAsync()
    {
        return base.Channel.LatestRGBImageAsync();
    }
    
    public byte[] LatestJPEGImage()
    {
        return base.Channel.LatestJPEGImage();
    }
    
    public System.Threading.Tasks.Task<byte[]> LatestJPEGImageAsync()
    {
        return base.Channel.LatestJPEGImageAsync();
    }
}
